# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wav_streamer.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12wav_streamer.proto\x12\x0bwavstreamer\"\x1c\n\x07WavData\x12\x11\n\twaw_chunk\x18\x01 \x01(\x0c\"\x0e\n\x0c\x45mptyRequest2O\n\x0bWavStreamer\x12@\n\x0bWavStreamer\x12\x19.wavstreamer.EmptyRequest\x1a\x14.wavstreamer.WavData0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wav_streamer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WAVDATA']._serialized_start=35
  _globals['_WAVDATA']._serialized_end=63
  _globals['_EMPTYREQUEST']._serialized_start=65
  _globals['_EMPTYREQUEST']._serialized_end=79
  _globals['_WAVSTREAMER']._serialized_start=81
  _globals['_WAVSTREAMER']._serialized_end=160
# @@protoc_insertion_point(module_scope)
