services:
  broker:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker
    container_name: broker
    network_mode: "host"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:29092,PLAINTEXT_HOST://192.168.11.60:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:29093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_METADATA_LOG_DIR: "/var/lib/kafka/data"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka-data:/var/lib/kafka/data
    user: "0:0"
    restart: unless-stopped
    command: >
      bash -c "
        mkdir -p /var/lib/kafka/data
        chmod -R 777 /var/lib/kafka/data 

        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          echo 'Formatting Kafka storage...'
          kafka-storage format -t $${CLUSTER_ID} -c /etc/kafka/kafka.properties
        fi

        /etc/confluent/docker/run
      "

  orchestrator:
    build:
      context: ../ProgramsOnRPI
      dockerfile: ../Docker/DockerfileKafkaOrchestrator.dockerfile
    container_name: kafka-orchestrator
    depends_on:
      - broker
    network_mode: "host"
    privileged: true
    restart: unless-stopped
volumes:
  kafka-data:
    driver: local