# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wav_streamer_pb2 as wav__streamer__pb2


class WavStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WavStreamer = channel.unary_stream(
                '/wavstreamer.WavStreamer/WavStreamer',
                request_serializer=wav__streamer__pb2.EmptyRequest.SerializeToString,
                response_deserializer=wav__streamer__pb2.WavData.FromString,
                )


class WavStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WavStreamer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WavStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WavStreamer': grpc.unary_stream_rpc_method_handler(
                    servicer.WavStreamer,
                    request_deserializer=wav__streamer__pb2.EmptyRequest.FromString,
                    response_serializer=wav__streamer__pb2.WavData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wavstreamer.WavStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WavStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WavStreamer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/wavstreamer.WavStreamer/WavStreamer',
            wav__streamer__pb2.EmptyRequest.SerializeToString,
            wav__streamer__pb2.WavData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
