# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spectrogram.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'spectrogram.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11spectrogram.proto\"L\n\x12SpectrogramRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\"\n\x06params\x18\x02 \x01(\x0b\x32\x12.SpectrogramParams\"\x8e\x01\n\x11SpectrogramParams\x12\x13\n\x0bwindow_type\x18\x01 \x01(\t\x12\x11\n\tn_segment\x18\x02 \x01(\x05\x12\x17\n\x0fhighpass_cutoff\x18\x03 \x01(\x05\x12\x17\n\x0f\x63olor_scale_min\x18\x04 \x01(\x02\x12\x1f\n\x17max_displayed_frequency\x18\x05 \x01(\x05\"K\n\x0fSpectrogramData\x12\x13\n\x0b\x66requencies\x18\x01 \x03(\x02\x12\r\n\x05times\x18\x02 \x03(\x02\x12\x14\n\x0cpower_levels\x18\x03 \x03(\x02\x32R\n\x12SpectrogramService\x12<\n\x11StreamSpectrogram\x12\x13.SpectrogramRequest\x1a\x10.SpectrogramData(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spectrogram_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPECTROGRAMREQUEST']._serialized_start=21
  _globals['_SPECTROGRAMREQUEST']._serialized_end=97
  _globals['_SPECTROGRAMPARAMS']._serialized_start=100
  _globals['_SPECTROGRAMPARAMS']._serialized_end=242
  _globals['_SPECTROGRAMDATA']._serialized_start=244
  _globals['_SPECTROGRAMDATA']._serialized_end=319
  _globals['_SPECTROGRAMSERVICE']._serialized_start=321
  _globals['_SPECTROGRAMSERVICE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
