# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spectrogram_generator_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'spectrogram_generator_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#spectrogram_generator_service.proto\x12\x14spectrogramgenerator\"\x8c\x01\n\x1bSpectrogramGeneratorRequest\x12\x13\n\x0bwindow_type\x18\x01 \x01(\t\x12\x11\n\tn_samples\x18\x02 \x01(\x05\x12\x18\n\x10\x66requency_cutoff\x18\x03 \x01(\x02\x12\x17\n\x0fspectrogram_min\x18\x04 \x01(\x05\x12\x12\n\nuri_to_wav\x18\x05 \x01(\t\"C\n\x1cSpectrogramGeneratorResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nuri_to_png\x18\x02 \x01(\t2\x94\x01\n\x14SpectrogramGenerator\x12|\n\x13GenerateSpectrogram\x12\x31.spectrogramgenerator.SpectrogramGeneratorRequest\x1a\x32.spectrogramgenerator.SpectrogramGeneratorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spectrogram_generator_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPECTROGRAMGENERATORREQUEST']._serialized_start=62
  _globals['_SPECTROGRAMGENERATORREQUEST']._serialized_end=202
  _globals['_SPECTROGRAMGENERATORRESPONSE']._serialized_start=204
  _globals['_SPECTROGRAMGENERATORRESPONSE']._serialized_end=271
  _globals['_SPECTROGRAMGENERATOR']._serialized_start=274
  _globals['_SPECTROGRAMGENERATOR']._serialized_end=422
# @@protoc_insertion_point(module_scope)
